### PR TITLE
Add full name on admin order page

### LINKED ISSUE #287: Make distinguishing between people easier
If several people with the same name have ordered in the same shift, it is not easy to distinguish between these people, especially if they have ordered the same thing. If everyone's association is shown in the list, this could solve the problem a bit, but if two people of the same association have the same name, perhaps add (the first X letters of) the last name so the tosticie members know whose order is first.

### PR DESCRIPTION
**Pull request by DeD1rk**
Closes #287.

This simple solution should help solve the problem of multiple Max/Tims.

Try out by just looking at the order list.

### CODE REVIEW

**Comment by DeD1rk** [comment]
Okay actually this will look pretty strange in some other templates

**Comment by JobDoesburg** [comment]
I would just add it to the order list, maybe with the full last name if not on mobile layout

**Comment by wkuijltjes** [comment]
Adding only the first character of the last name doesn't mean that now all the names on the list are unique, which is more importantly than displaying the first letter of the last name for everybody. E.g. distinguish between Tim van X, Tim van der Y and Tim Z (where Z[0] = V)? Is it too difficult to just check the other users on the list and add ```n``` characters of the last name until a unique user has been created (assuming non-identical names)?

Also, this doesn't resolve the fact that some people might not prefer their official name on the list anyway as they are only known by their nickname (and/or don't like their official name). Displaying a chosen/set ```display_name``` (perhaps in parentheses) might resolve some of the non-unique names issues.

**Comment by KiOui** [comment]
I agree that @wkuijltjes is right about distinguishing the names but I don't think it will be a really big problem as there might not be a lot of same first and last names.

I don't think that we should do a `display_name` because that will definitely be abused (as an example the Thalia website and Jen's photo).

**Comment by DeD1rk** [comment]
Okay I changed it to show first and last name on the shift admin, regardless of any overrides. I think this is fine privacy-wise: tosticie members can see full names anyway in the admin, and it works to distinguish everyone as tosticie member. Users themselves have an icon next to their own orders anyway, so I don't think uniqueness matters there anyway. 

Another note on privacy: the API returns full names to everyone, while not displaying them offers _some_ privacy, it's not like they are then not public any more.

**Review by JobDoesburg — APPROVED** [review]

**Comment by JobDoesburg** [comment]
@DeD1rk can you fix the merge conflict

**Pull request merged**
