### PR TITLE
Update to bootstrap 5, fix admin errors

### PR DESCRIPTION
**Pull request by KiOui**
Changed the following:

- Updated Bootstrap 4 to Bootstrap 5
- Removed jQuery
- Changed track search API endpoint, it was echoing an identifier (this was because the old javascript code was a bit stupid, oops)
- Removed Toastr and added TaTa.js (because Toastr uses jQuery)
- Recreated the way we do refreshes on the page, API calls are now not done per function hook but per API endpoint. Functions can register themselves on API data they need. API calls are then done for all functions registered on an endpoint. In the old case, if we had two functions that required the same API data, we did two API requests. Now we only do one and supply the same data to all functions registered on endpoints.

I moved most of the general Javascript functions to the Vue objects as fetch operations are not really easily generalizable.

Test this pull request by testing if all asynchronous (javascript) operations work. Also check the styling of the pages.

### CODE REVIEW

**Comment by JobDoesburg** [comment]
One small remark already: we might want to use bootstrap5 offcanvas elements for the styling

**Comment by JobDoesburg** [comment]
afbeelding
The opacity here should not be on the message

**Comment by JobDoesburg** [comment]
afbeelding
there should be padding on the left side of the button here

**Comment by JobDoesburg** [comment]
afbeelding
there should be padding on the left side of the icon here

**Comment by JobDoesburg** [comment]
afbeelding
the close button is not correctly styled

**Comment by JobDoesburg** [comment]
afbeelding
where are the '+5' and 'toggle accept orders' buttons?

**Comment by JobDoesburg** [comment]
afbeelding
this says "join shift" even though I was already joined?

**Comment by JobDoesburg** [comment]
afbeelding
Javascript error

**Comment by JobDoesburg** [comment]
afbeelding
this button does not work

**Comment by JobDoesburg** [comment]
afbeelding
Visiting the calendar is broken

**Comment by JobDoesburg** [comment]
afbeelding
"capacity reached" does not show the current amout of orders (it should display "(1/50)" instead of "(/50)")

**Comment by JobDoesburg** [comment]
afbeelding
This turns out to be possible

**Comment by JobDoesburg** [comment]
After placing an order, the user should be redirected to the shift overview instead of staying at the 'place an order' page

**Comment by JobDoesburg** [comment]
afbeelding
I would expect the order of columns to be reverse

**Comment by JobDoesburg** [comment]
afbeelding
I can't get this to work

**Comment by JobDoesburg** [comment]
afbeelding
I always keep getting a 403 error on every spotify request

**Comment by JobDoesburg** [comment]
afbeelding
not all fields in the inline should be readonly

**Comment by JobDoesburg** [comment]
afbeelding

**Comment by JobDoesburg** [comment]
afbeelding
These should have datetimepickers

**Comment by JobDoesburg** [comment]
afbeelding
hovering this list breaks readability

**Comment by JobDoesburg** [comment]
afbeelding
It should be visible if the shifts are finalized (list_display and list_filter)

**Comment by KiOui** [comment]
Okay so turned out merging with `master` broke everything, #fun.

**Comment by KiOui** [comment]
Why do I have to add migrations to my pull request from the `sp` app?

**Comment by KiOui** [comment]
> afbeelding
> 
> I would expect the order of columns to be reverse

I did not fix this, please create an issue

**Comment by KiOui** [comment]
> afbeelding
> 
> not all fields in the inline should be readonly

This is out of scope for this pull request

**Comment by KiOui** [comment]
> afbeelding

This is also out of scope

**Comment by KiOui** [comment]
> afbeelding
> 
> It should be visible if the shifts are finalized (list_display and list_filter). Also, if the shift is finalized, all fields should be read_only

And this as well

**Comment by KiOui** [comment]
I commented the stuff that I did not change, these things were already in the repository before migrating to bootstrap 5. You can open issues for them if you want to.

**Comment by JobDoesburg** [comment]
I'm still getting only 403's on thaliedje api requests

**Comment by JobDoesburg** [comment]
An overview of other things that should be fixed:

- Change column order of user profile data sections
- Not all shift-admin fields should be read-only
- Fix capitalization in the admin
- list_display and list_filter for finalized shifts
- Product admin broken
- Order admin broken

**Review by JobDoesburg — APPROVED** [review]

**Pull request merged**
