### PR TITLE
explitictly unset prioritize on deprioritizing

### LINKED ISSUE #525: Prioritise/deprioritise conflict
When an order has priority (because someone is a tosticie member for example) and you deprioritise your own order, the order stays on top of the order list, since both the prioritise and deprioritise are on. It would be nice if these could be exclusive, meaning the order is either prioritised or deprioritised, and not both.

### PR DESCRIPTION
**Pull request by mark-boute**
closes #525
Make sure that the prioritize flag is unset on de-prioritizing.

### CODE REVIEW

**Comment by mark-boute** [comment]
@KiOui any idea why this is not unsetting the flag currently? I am stuck

**Comment by KiOui** [comment]
> @KiOui any idea why this is not unsetting the flag currently? I am stuck

The `OrderSerialize` has the `prioritize` field as read-only. It should be altered in such a way that `deprioritize` overrules `prioritize`. I think we have three options here:

- The best option is to just create a new field "priority" with three options: "deprioritize", "normal" or "prioritize". This option does however require a database migration.
- We could also maybe adjust the `save` method to automatically set `prioritize` to `false` whenever `deprioritize` is `true`.
- Or we could change the `OrderSerializer` to also accept the `prioritize` field and then adjust the `OrderRetrieveUpdateDestroyAPIView` such that it only accepts changes to the `prioritize` field if the user has permission.

**Comment by JobDoesburg** [comment]
For me, this is a frontend thingy. There's nothing wrong with both prioritize and deprioritize flags set in principle. It's just not the behavior people expect if they hit the button. So keep it in the API / serializer

**Comment by KiOui** [comment]
I don't agree with you on that point. It's weird to have an order that both has priority and does not have priority. So I think migrating this to just one field that can either be prioritized, normal or deprioritized is the best option.

**Comment by KiOui** [comment]
This has been fixed in #534

**Pull request closed without merging**
